src/faypublic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),

    # authentication
    path('register/', views.user_register, name="user_register"),
    path('login/', auth_views.LoginView.as_view(template_name='user_login.html'), name="user_login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name="user_logout"),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='user_password_reset.html'), name="password_reset"),
    path('reset-password/done/',  auth_views.PasswordResetDoneView.as_view(template_name='user_password_reset_done.html'), name="password_reset_done"),
    path('reset-password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user_password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user_password_reset_complete.html'), name="password_reset_complete"),

    # profile
    path('profile/', include('userprofile.urls')),

    # class
    path('classes/', include('classes.urls')),
    path('equipment/', include('inventory.urls')),
    # path('test-notifications/', views.test_notifications, name="test_notifications"),
    path('report/', include('report.urls'))
]

src/project/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.projects, name="user_projects"),
    path('<int:id>/', views.project, name="project"),
    path('cancel/<project_id>/', views.cancel_project, name='cancel_project')
]

src/report/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.reporting, name="reporting"),
]

src/project/models.py
import arrow, os
from django.db import models
from userprofile.models import UserProfile
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from faypublic.settings import DEBUG

SUBMITTED = 'SUBMITTED'
SCHEDULED = 'SCHEDULED'
REJECTED = 'REJECTED'

PROGRAM_REQUEST_STATUS = (
    (SUBMITTED, 'Submitted'),
    (SCHEDULED, 'Approved'),
    (REJECTED, 'Rejected')
)


def handle_file_upload(project, filename):
    timestamp = arrow.utcnow().timestamp
    return 'uploads/{0}/project-uploads/{1}-{2}'.format(project.owner.username, timestamp, filename)


def validate_video_extension(file):
    valid_extensions = ['.mp4']
    ext = os.path.splitext(file.name)[1]
    if not ext.lower() in valid_extensions:
        raise ValidationError('Invalid file type; please use .mp4')


class Project(models.Model):
    class Meta:
        verbose_name = "project"
        verbose_name_plural = "projects"

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_projects')
    users = models.ManyToManyField(User)
    title = models.CharField(max_length=255, null=True, blank=False)
    created = models.DateField(auto_now_add=True)
    description = models.TextField(null=True, blank=True)
    expected_completion_date = models.DateField(null=True, blank=False)
    media_link = models.CharField(max_length=255, null=True, blank=True)
    uploaded_file = models.FileField(upload_to=handle_file_upload, null=True, blank=True, validators=[validate_video_extension])

    def __str__(self):
        return self.title + ' - ' + str(self.owner)

    def __unicode__(self):
        return self.title + ' - ' + str(self.owner)

    def get_absolute_url(self):
        return "/profile/projects/%i/" % self.id

    def get_uploaded_file_url(self):
        if DEBUG:
            return '/static/media/' + self.uploaded_file.url
        return self.uploaded_file.url



class ProgramRequest(models.Model):
    class Meta:
        verbose_name = "program request"
        verbose_name_plural = "program requests"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=False)
    description = models.TextField(null=True, blank=True)
    requested_on = models.DateField(auto_now_add=True)
    requested_play_date = models.DateTimeField(null=True, blank=False)
    media_link = models.URLField(max_length=500, null=True, blank=False)
    status = models.CharField(
        max_length = 20,
        choices = PROGRAM_REQUEST_STATUS,
        default = SUBMITTED
    )
    contains_mature_content = models.BooleanField(default=False)


    def __str__(self):
        return self.title
    
    def __unicode__(self):
        return self.title

src/project/forms.py
from django.forms import Form, ModelForm
from .models import Project, ProgramRequest
from django import forms
from functools import partial
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class SmallProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ['owner', 'users', 'description']
        widgets = {
        	'expected_completion_date' : DateInput(),
        }

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ['owner', 'users', 'uploaded_file']
        widgets = {
        	'expected_completion_date' : DateInput(),
        }



def validate_user_exists(user_email):
    try:
        user = User.objects.get(email=user_email)
    except User.DoesNotExist:
        raise ValidationError('User does not exist')


class ProjectInviteUserForm(Form):
    invited_user_email = forms.EmailField(
        label='Invite user',
        required=True,
        validators=[validate_user_exists]
    )


class ProjectProgramRequestForm(ModelForm):
    class Meta:
        model = ProgramRequest
        exclude = ['user', 'title', 'description', 'requested_on', 'media_link', 'status']
        widgets = {
            'requested_play_date': DateInput()
        }

class ProgramRequestForm(ModelForm):
    class Meta:
        model = ProgramRequest
        exclude = ['user', 'requested_on', 'status']
        widgets = {
            'requested_play_date': DateInput()
        }

src/project/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Project
from .forms import ProjectForm, SmallProjectForm, ProjectInviteUserForm, ProjectProgramRequestForm
from userprofile.models import UserProfile
from django.contrib.auth.models import User
from django.core.mail import send_mail

# Create your views here.
@login_required
def projects(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)

    project_form = SmallProjectForm(request.POST)

    if project_form.is_valid():
        project =  project_form.save(commit=False)
        project.owner = request.user
        project.save()

    return render(
        request,
        'projects.html',
        context={
            'userprofile': userprofile,
            'project_form': SmallProjectForm(),
        }
    )


@login_required
def project(request, id):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    project = get_object_or_404(Project, id=id)

    if not project in userprofile.projects():
        return redirect('/profile/projects/')

    invite_user_form = ProjectInviteUserForm(request.POST)
    if request.method == 'POST' and invite_user_form.is_valid():
        email = invite_user_form.cleaned_data['invited_user_email']

        if email != request.user.email:
            invited_user = get_object_or_404(User, email=email)
            project.users.add(invited_user)

    program_request = ProjectProgramRequestForm(request.POST)
    if request.method == 'POST' and program_request.is_valid() and project.media_link:
        req = program_request.save(commit=False)
        req.user = request.user
        req.title = project.title
        req.description = project.description
        req.media_link = project.media_link
        req.save()

        redirect('/profile/requests/')

    project_form = ProjectForm(request.POST, request.FILES, instance=project)
    if request.method == 'POST' and project_form.is_valid():
        project = project_form.save()

    return render(
        request,
        'project.html',
        context={
            'project': project,
            'project_form': ProjectForm(instance=project),
            'invite_user_form': ProjectInviteUserForm(),
            'project_program_request_form': ProjectProgramRequestForm()
        }
    )


@login_required
def cancel_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.owner == request.user:
        project.delete()

    return redirect('user_projects')

src/project/templates/project.html
{% extends 'profile_base.html' %}

{% block title %}{{ project.title }}{% endblock title %}

{% block content %}

<head>
    <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js" integrity="sha384-nVi8MaibAtVMFZb4R1zHUW/DsTJpG/YwPknbGABVOgk5s6Vhopl6XQD/pTCG/DKB" crossorigin="anonymous"></script>
    <!-- added for date picker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<script>
$(document).ready(function() {
    $('.datepicker').datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "1900:2050",
        defaultDate: new Date(),});
});
</script>

<div class="container project-container">
    <h1>{{ project.title }}</h1>
    <p>Created: {{ project.created }}</p>
    <p>{{ project.description }}</p>
    <p>Owner: {{ project.owner }}</p>
    {% for user in project.users.all %}
        <p>Member: {{ user }}</p>
    {% endfor %}
</div>
<div class="container">
    <h3>Invite user</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class = "wrapper">
            <i class="fa fa-user" id="fa-edit-prof"></i>
            <label>Invite user by email:</label>
            {{ invite_user_form.invited_user_email }}
            <!-- <p id="pass-help">Expected completion date</p> -->
        </div>
        <br>
        <input type="submit" class="button green-bg" value="Invite" style="width:100%"/>
    </form>
</div>
<div class="container">
    <h3>Program request</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ project_program_request_form.as_p }}
        <input type="submit" class="button green-bg" value="Submit request" style="width:100%"/>
    </form>
</div>
<div class="container">
    <h3>Project Details</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class = "wrapper">
            <i class="fas fa-pencil-alt" id="fa-edit-prof"></i>
            <label>{{ project_form.title.label }}</label>
            {{ project_form.title }}
        </div>
        <br>
        <div class = "wrapper">
            <label>{{ project_form.description.label }}</label>
            {{ project_form.description }}
        </div>
        <br>
        <div class = "wrapper">
            <i class="fa fa-calendar" id="fa-edit-prof"></i>
            <label>{{ project_form.expected_completion_date.label }}</label>
            {{ project_form.expected_completion_date }}
            <!-- <p id="pass-help">Expected completion date</p> -->
        </div>
        <br>
        {% for error in project_form.uploaded_file.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        <div class = "wrapper">
            <i class="fa fa-link" id="fa-edit-prof"></i>
            <label>Media link</label>
            {{ project_form.media_link }}
            <!-- <p id="pass-help">Expected completion date</p> -->
        </div>
        <br>
        <input type="submit" class="button green-bg" value="Save" style="width:100%"/>
    </form>
</div>
{% endblock content %}

src/project/templates/projects.html
{% extends 'profile_base.html' %}

{% block title %}Your Projects{% endblock title %}

{% block content %}

<div class="container">
    <h1>Your Projects</h1>
    <p>This is a way to collaborate on and submit projects you're working on to play on-air</p>
</div>

<div class="container">
    <h2>Projects you've started</h2>
    <table class="table">
    {% for project in request.user.owner_projects.all %}
        <tr class="row">
            <td>
                <span class="title">
                    <a href="{{ project.get_absolute_url }}">
                        {{ project.title }}
                    </a>
                </span>
                <span class="info">
                    Created: {{ project.created }}
                </span>
            </td>
            <td class="right">
                Estimated completion: {{ project.expected_completion_date }}

                <br/><br/>

                <a href="/profile/projects/cancel/{{ project.id }}" class="button red-bg" onclick="return confirm('Are you sure?')">Cancel</a>
            </td>
        </tr>

    {% empty %}

    <tr class="row">
            <td>
                <span class="title">
                    No projects here!
                </span>
            </td>
        </tr>

    {% endfor %}
    </table>

    <h2>Projects you work on</h2>
    <table class="table">
    {% for project in request.user.project_set.all %}
        <tr class="row">
            <td>
                <span class="title">
                    <a href="{{ project.get_absolute_url }}">
                        {{ project.title }}
                    </a>
                </span>
                <span class="info">
                    Created: {{ project.created }} <br/>
                    Estimated completion: {{ project.expected_completion_date }}
                </span>
            </td>
            <td class="right">
                {{ project.number_of_submissions }} submission(s)
            </td>
        </tr>

    {% empty %}

        <tr class="row">
            <td>
                <span class="title">
                    No projects here!
                </span>
            </td>
        </tr>
    
    {% endfor %}
    </table>
</div>

<div class="container">
    <h2>Create a new project:</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class = "wrapper">
            <i class="fas fa-pencil-alt" id="fa-icon"></i>
            {{ project_form.title }}
        </div>
        <br>
        <div class = "wrapper">
            <i class="fa fa-calendar" id="fa-icon"></i>
            {{ project_form.expected_completion_date }}
            <p id="pass-help">Expected completion date</p>
        </div>
        <br>
        <input type="submit" class="button green-bg" value="Create New Project" style="width:100%"/>
    </form>
</div>

{% endblock content %}