src/faypublic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),

    # authentication
    path('register/', views.user_register, name="user_register"),
    path('login/', auth_views.LoginView.as_view(template_name='user_login.html'), name="user_login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name="user_logout"),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='user_password_reset.html'), name="password_reset"),
    path('reset-password/done/',  auth_views.PasswordResetDoneView.as_view(template_name='user_password_reset_done.html'), name="password_reset_done"),
    path('reset-password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user_password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user_password_reset_complete.html'), name="password_reset_complete"),

    # profile
    path('profile/', include('userprofile.urls')),

    # class
    path('classes/', include('classes.urls')),
    path('equipment/', include('inventory.urls')),
    # path('test-notifications/', views.test_notifications, name="test_notifications"),
    path('report/', include('report.urls'))
]

src/report/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.reporting, name="reporting"),
]

src/project/models.py
import arrow, os
from django.db import models
from userprofile.models import UserProfile
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from faypublic.settings import DEBUG

SUBMITTED = 'SUBMITTED'
SCHEDULED = 'SCHEDULED'
REJECTED = 'REJECTED'

PROGRAM_REQUEST_STATUS = (
    (SUBMITTED, 'Submitted'),
    (SCHEDULED, 'Approved'),
    (REJECTED, 'Rejected')
)


def handle_file_upload(project, filename):
    timestamp = arrow.utcnow().timestamp
    return 'uploads/{0}/project-uploads/{1}-{2}'.format(project.owner.username, timestamp, filename)


def validate_video_extension(file):
    valid_extensions = ['.mp4']
    ext = os.path.splitext(file.name)[1]
    if not ext.lower() in valid_extensions:
        raise ValidationError('Invalid file type; please use .mp4')


class Project(models.Model):
    class Meta:
        verbose_name = "project"
        verbose_name_plural = "projects"

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_projects')
    users = models.ManyToManyField(User)
    title = models.CharField(max_length=255, null=True, blank=False)
    created = models.DateField(auto_now_add=True)
    description = models.TextField(null=True, blank=True)
    expected_completion_date = models.DateField(null=True, blank=False)
    media_link = models.CharField(max_length=255, null=True, blank=True)
    uploaded_file = models.FileField(upload_to=handle_file_upload, null=True, blank=True, validators=[validate_video_extension])

    def __str__(self):
        return self.title + ' - ' + str(self.owner)

    def __unicode__(self):
        return self.title + ' - ' + str(self.owner)

    def get_absolute_url(self):
        return "/profile/projects/%i/" % self.id

    def get_uploaded_file_url(self):
        if DEBUG:
            return '/static/media/' + self.uploaded_file.url
        return self.uploaded_file.url



class ProgramRequest(models.Model):
    class Meta:
        verbose_name = "program request"
        verbose_name_plural = "program requests"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=False)
    description = models.TextField(null=True, blank=True)
    requested_on = models.DateField(auto_now_add=True)
    requested_play_date = models.DateTimeField(null=True, blank=False)
    media_link = models.URLField(max_length=500, null=True, blank=False)
    status = models.CharField(
        max_length = 20,
        choices = PROGRAM_REQUEST_STATUS,
        default = SUBMITTED
    )
    contains_mature_content = models.BooleanField(default=False)


    def __str__(self):
        return self.title
    
    def __unicode__(self):
        return self.title

src/faypublic/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import Form, ModelForm

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

        # Altering help text
        for fieldname in ['password1']:
        	self.fields[fieldname].help_text = "Must contain 8 characters, with at least 1 letter"

src/faypublic/views.py
import arrow
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from userprofile.models import UserProfile
from inventory.models import EquipmentCheckout
from classes.models import ClassSection
from .tasks import send_equipment_pickup_reminder, send_equipment_due_reminder, send_equipment_overdue_notification, send_class_registration_reminder

def home(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        checkouts = EquipmentCheckout.objects.filter(user=request.user).order_by('-due_date', '-checkout_date')
        class_registrations = request.user.classregistration_set.all().order_by('-class_section__date')

        userprofile = get_object_or_404(UserProfile, user=request.user)

        return render(
            request,
            'home.html',
            context={
                'checkouts': checkouts,
                'class_registrations': class_registrations,
                'profile': userprofile,
            }
        )
    elif request.user.is_authenticated:
        today = arrow.get(timezone.now())
        today_start = today.floor('day').datetime
        today_end = today.ceil('day').datetime

        checkouts = EquipmentCheckout.objects.filter(due_date__gte=today_end) # todo: order by params? why u no work

        overdue_checkouts = EquipmentCheckout.objects.filter(
            due_date__lte=today_end,
            checkout_status='CHECKED_OUT'
        ).order_by('-due_date', '-checkout_date')

        todays_classes = ClassSection.objects.filter(
            date__gte=today_start,
            date__lte=today_end
        )
        return render(
            request,
            'admin_home.html',
            context={
                'checkouts': checkouts,
                'overdue_checkouts': overdue_checkouts,
                'todays_classes': todays_classes
            }
        )
    else:
        return render(
            request,
            'home_login.html',
            context={
            }
        )

def user_register(request):
    form = UserRegistrationForm(request.POST or None)

    street_address = request.POST.get('street_address')
    city = request.POST.get('city')
    state = request.POST.get('state')
    zipcode = request.POST.get('zip_code')
    phone_number = request.POST.get('phone_number')

    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        raw_pass = form.cleaned_data.get('password1')
        user = authenticate(
            username=username,
            password=raw_pass
        )
        login(request, user)
        userprofile = UserProfile.objects.create(
            user=user,
            street_address=street_address,
            city=city,
            state=state,
            zipcode=zipcode,
            phone_number=phone_number
        )
        userprofile.save()

        if request.GET.get('next'):
            requested_page = request.GET['next']
            return redirect(requested_page)

        return redirect('edit_profile')

    return render(
        request,
        'user_register.html',
        context={
            'form': form
        }
    )

    if request.POST:
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)

    if profile_form.is_valid():
        userprofile = profile_form.save(commit=False)
        user_get_email_reminders = request.POST.get('user_get_email_reminders')
        userprofile.get_email_reminders = True if user_get_email_reminders == 'on' else False
        user_get_sms_reminders = request.POST.get('user_get_sms_reminders')
        userprofile.get_sms_reminders = True if user_get_sms_reminders == 'on' else False
        userprofile.save()

        
        request.user.first_name = user_first_name
        request.user.last_name = user_last_name
        request.user.email = user_email
        request.user.save()

    return render(
        request,
        'edit_profile.html',
        context={
            'name': request.user.first_name + ' ' + request.user.last_name,
            'profile': userprofile,
            'profile_form': profile_form
        }
    )

def test_notifications(request):
    send_equipment_pickup_reminder()
    send_equipment_due_reminder()
    send_equipment_overdue_notification()
    send_class_registration_reminder()
    return redirect('/')

src/faypublic/templates/admin_home.html
{% extends 'snapshot_base.html' %}

{% block title %}Fayetteville Public Television{% endblock title %}

{% block content %}

    <div class="container">
        <h2>Current checkouts</h2>

        <table class="table">
            <tr class="row">
                <th>User</th>
                <th>Equipment</th>
            </tr>

            {% for checkout in checkouts %}

             <tr class="row">
                <td>
                    <b>{{ checkout.user_name }}</b> <br/>
                    {{ checkout.user.email }} - {{ checkout.user_profile.phone_number }}
                </td>
                <td>
                    <b>{{ checkout.equipment.make }} {{ checkout.equipment.model }}</b> <br/>
                    <b>Checked out</b>: {{ checkout.checkout_date }} <br/>
                    <b>Due</b>: {{ checkout.due_date }} - {{ checkout.due_date_humanized }}
                </td>
             </tr>

            {% endfor %}

        </table>

    </div>

    <div class="container">
        <h2>Overdue checkouts</h2>

        <table class="table">
            <tr class="row">
                <th>User</th>
                <th>Equipment</th>
            </tr>

            {% for checkout in overdue_checkouts %}

             <tr class="row">
                <td>
                    <b>{{ checkout.user_name }}</b> <br/>
                    {{ checkout.user.email }} - {{ checkout.user_profile.phone_number }}
                </td>
                <td>
                    <b>{{ checkout.equipment.make }} {{ checkout.equipment.model }}</b> <br/>
                    <b>Checked out</b>: {{ checkout.checkout_date }} <br/>
                    <b>Due</b>: {{ checkout.due_date }} - {{ checkout.due_date_humanized }}
                </td>
             </tr>

            {% endfor %}

        </table>

    </div>

    <div class="container">
        <h2>Today's classes</h2>

        {% for class in todays_classes %}

            <table class="table">

                <tr class="row">
                    <th>{{ class.class_key.class_title }}</th>
                    <th>{{ class.date }} - {{ class.date_humanized }}</th>
                    <th>Registrations: {{ class.class_key.number_registered }}</th>
                </tr>

                {% for registration in class.classregistration_set.all %}
                    <tr class="row">
                        <td>{{ registration.user }}</td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endfor %}

            </table>

        {% endfor %}

    </div>

{% endblock content %}

src/faypublic/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="/static/css/base.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js" integrity="sha384-nVi8MaibAtVMFZb4R1zHUW/DsTJpG/YwPknbGABVOgk5s6Vhopl6XQD/pTCG/DKB" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- navbar highlight for active page -->
    <script>
        $(function(){
            $('a').each(function(){
                if ($(this).prop('href') == window.location.href) {
                    $(this).addClass('active'); $(this).parents('li').addClass('active');
                }
            });
        });
    </script>

</head>
<body>

    <nav class="navbar navbar-default" style="background-color: #f6d600;">
      <div class="container-fluid">

        <!-- Header -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar" style="border-color: black;">
                <span class="icon-bar" style="color: black;"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://www.faypublic.tv/" style="color: black;"><img src="/static/media/fptv_logo.png" class="navbar-image"/></a>
          </div>


        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="/" style="color: black;">
                <span class="fa fa-home" aria-hidden="true"></span>&nbsp; Home
              </a>
            </li>
            <li class="">
              <a href="/classes/" style="color: black;">
                <span class="fa fa-graduation-cap" aria-hidden="true"></span>&nbsp; Classes
              </a>
            </li>
            <li class="">
              <a href="/equipment/" style="color: black;">
                <span class="fa fa-video" aria-hidden="true"></span>&nbsp; Equipment
              </a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated and not user.is_superuser %}
              <li class="">
                <a href="/profile/" style="color: black;">
                  <span class="fa fa-user" aria-hidden="true"></span>&nbsp; Profile
                </a>
              </li>
              <li class="">
                <a href="/logout/" style="color: black;">
                  <span class="fa fa-sign-out-alt" aria-hidden="true"></span>&nbsp; Logout
                </a>
              </li>
            {% elif user.is_authenticated %}
                <li class="">
                    <a href="/admin/" style="color: black;">
                      <span class="fa fa-user" aria-hidden="true"></span>&nbsp; Admin
                    </a>
                  </li>
                  <li class="">
                    <a href="/logout/" style="color: black;">
                      <span class="fa fa-sign-out-alt" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                  </li>
            {% else %}
              <li class="">
                <a href="/login/" style="color: black;">
                  <span class="fa fa-sign-in-alt" aria-hidden="true"></span>&nbsp; Login
                </a>
              </li>
              <li class="">
                <a href="/register/" style="color: black;">
                  <span class="fas fa-clipboard" aria-hidden="true"></span>&nbsp; Register
                </a>
              </li>
            {% endif %}
          </ul>

        </div>

      </div>
      
    </nav>

    <div id="contact-footer">
        <div class="container">
        <p>
            Contact us: 
            <a href="tel:479-444-3433">(479) 444-3433</a> | <a href="mailto:info@faypublic.tv">info@faypublic.tv</a>
        </p>
        </div>
    </div>

    {% block pagecontent %}{% endblock pagecontent %}

    <script>
        $(document).ready(function() {
            $('.datepicker').datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1900:2050",
                defaultDate: new Date(),
            });
        
            $("#id_title").attr('placeholder', '{{project_form.title.label}}');
        });
    </script>

</body>
</html>

src/faypublic/templates/home.html
{% extends 'snapshot_base.html' %}

{% block title %}Fayetteville Public Television{% endblock title %}

{% block content %}
<head>
    <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js" integrity="sha384-nVi8MaibAtVMFZb4R1zHUW/DsTJpG/YwPknbGABVOgk5s6Vhopl6XQD/pTCG/DKB" crossorigin="anonymous"></script>
</head>

    <div class="container">

        <div class="container">

            <h1>Profile Snapshot:</h1>
            <h3>Your checkouts</h3>

            <table class="table">
            {% for checkout in checkouts %}

            <tr class="row">
                <td>
                    <span class="title">
                        {{ checkout.equipment.make }} {{ checkout.equipment.model }}
                    </span>
                    <span class="info">
                        Checked out: {{ checkout.checkout_date }} <br/>
                        Due: {{ checkout.due_date }}
                    </span>
                </td>
                <td class="right">
                    {% if checkout.checkout_status == 'RESERVED' %}

                        <span style="display: inline-block; vertical-align:middle;">
                            Reserved<br/>
                            Pick up {{ checkout.checkout_date }}<br/>
                            Due {{ checkout.due_date_humanized }}
                        </span>
                        <span style="display: inline-block; vertical-align:middle;" class="circle blue-bg"></span>

                    {% elif checkout.checkout_status == 'CHECKED_OUT' %}

                        <span style="display: inline-block; vertical-align:middle;">
                            Checked out<br/>
                            Due {{ checkout.due_date_humanized }}
                        </span>

                        <span style="display: inline-block; vertical-align:middle;" class="circle yellow-bg"></span>

                    {% elif checkout.checkout_status == 'RETURNED' %}

                        <span style="display: inline-block; vertical-align:middle;">
                            Returned
                        </span>
                        <span style="display: inline-block; vertical-align:middle;" class="circle green-bg"></span>

                    {% endif %}
                </td>
            </tr>

            {% empty %}
            
            <tr class="row">
                <td>
                    <span class="title">
                        You have nothing checked out!
                    </span>
                </td>
            </tr>

            {% endfor %}
            </table>
        </div>

        <div class="container">
            <h3>Your classes</h3>


            <table class="table">
            {% for reg in class_registrations %}

            <tr class="row">
                <td>
                    <span class="title">
                        {{ reg.class_title }}
                    </span>
                    <span class="info">
                        {{ reg.class_section.date_humanized }}
                    </span>
                </td>
                <td class="right">
                    <span>
                        {{ reg.section }}<br/>
                        {% if reg.completed and reg.score_percentage %}
                            Complete - {{ reg.score_percentage }}%
                        {% else %}
                            Incomplete
                        {% endif %}
                    </span>
                </td>
            </tr>

            {% empty %}

            <tr class="row">
                <td>
                    <span class="title">
                        You're not registered for any classes!
                    </span>
                </td>
            </tr>

            {% endfor %}
            </table>
        </div>

        <div class="container">

            <h3>Your projects</h3>

            <table class="table">
            {% for project in profile.projects %}
                <tr class="row">
                    <td>
                        <span class="title">
                            <a href="{{ project.get_absolute_url }}">
                                {{ project.title }}
                            </a>
                        </span>
                        <span class="info">
                            Created: {{ project.created }}
                        </span>
                    </td>
                </tr>

            {% empty %}

                <tr class="row">
                    <td>
                        <span class="title">
                            No projects here!
                        </span>
                    </td>
                </tr>

            {% endfor %}
            </table>
            <a href="/profile/projects" class="button green-bg">Start a project</a>

        </div>
        
    </div>

{% endblock content %}

src/faypublic/templates/home_login.html
{% extends 'base.html' %}

{% block title %}Fayetteville Public Television{% endblock title %}

{% block pagecontent %}
<head>
    <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js" integrity="sha384-nVi8MaibAtVMFZb4R1zHUW/DsTJpG/YwPknbGABVOgk5s6Vhopl6XQD/pTCG/DKB" crossorigin="anonymous"></script>
</head>

    <div class="container">
        <h1 style="text-align: center;">Please login or register!</h1>
        <img src="/static/media/fptv_logo.png" style="display:block; width: 200px; margin:0px auto;"/>
        <hr>
        <div class="hours-row">
            <div class="button-column">
                <a href="/login/" class="button green-bg" style="width: 90%">Login</a>
            </div>
            <div class="button-column">
                <a href="/register/" class="button blue-bg" style="width: 90%">Register</a>
            </div>
        </div>
    </div>

{% endblock pagecontent %}

src/faypublic/templates/snapshot_base.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block pagecontent %}

<div class="container flex-container">
    <div class="container flex-item sidebar submenu">
        <h1>Fayetteville Public Television</h1>
        <p>Welcome to FPTV's production and class management application.</p>
        
        {% if request.user.is_authenticated %}

            {% if request.user.is_superuser %}
                <p>
                    <a href="/admin/" class="button green-bg">Admin</a>
                    <a href="/report/" class="button blue-bg">Report</a>
                    <a href="/equipment/admin-calendar/" class="button red-bg">Equipment Calendar</a>
                </p>
            {% else %}
                <p>
                    <a href="/profile/" class="button green-bg">Your Profile</a>
                </p>
            {% endif %}
        <hr>
        <p>
            <a href="tel:479-444-3433">(479) 444-3433</a>
        </p>
        <p>
            101 West Rock Street<br/>
            Fayetteville, AR 72701
        </p>
        <div class="hours-row">
            <div class="hours-column">
                <p>
                    Monday:<br/>
                    Tuesday:<br/>
                    Wednesday:<br/>
                    Thursday:<br/>
                    Friday:<br/>
                    Saturday:<br/>
                    Sunday:
                </p>
            </div>
            <div class="hours-column">
                <p>
                    10:00am-7:00pm<br/>
                    10:00am-7:00pm<br/>
                    CLOSED<br/>
                    10:00am-7:00pm<br/>
                    10:00am-7:00pm<br/>
                    10:00am-7:00pm<br/>
                    CLOSED
                </p>
            </div>
        </div>
        {% else %}
        <p>
            <a href="/login/" class="button green-bg">Login</a>
            <a href="/register/" class="button blue-bg">Register</a>
        </p>
        <hr>
        <p>
            <a href="tel:479-444-3433">(479) 444-3433</a>
        </p>
        <p>
            101 West Rock Street<br/>
            Fayetteville, AR 72701
        </p>
        <div class="hours-row">
            <div class="hours-column">
                <p>
                    Monday:<br/>
                    Tuesday:<br/>
                    Wednesday:<br/>
                    Thursday:<br/>
                    Friday:<br/>
                    Saturday:<br/>
                    Sunday:
                </p>
            </div>
            <div class="hours-column">
                <p>
                    10:00am-7:00pm<br/>
                    10:00am-7:00pm<br/>
                    CLOSED<br/>
                    10:00am-7:00pm<br/>
                    10:00am-7:00pm<br/>
                    10:00am-7:00pm<br/>
                    CLOSED
                </p>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="flex-item sidebar content">
        {% block content %}{% endblock content %}
    </div>
</div>

{% endblock pagecontent %}

src/faypublic/templates/user_login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block pagecontent %}

<head>
    <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js" integrity="sha384-nVi8MaibAtVMFZb4R1zHUW/DsTJpG/YwPknbGABVOgk5s6Vhopl6XQD/pTCG/DKB" crossorigin="anonymous"></script>
</head>

<div class="container">
    <h1>Login</h1>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
        {{ form.username.errors }}
        <div class = "wrapper">
            <i class="fas fa-user-circle" id="fa-icon"></i>
            {{ form.username }}
        </div>
        <br>
        <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
        {{ form.password.errors }}
        <div class = "wrapper">
        	<i class="fa fa-unlock-alt" id="fa-icon"></i>
        	{{ form.password }}
        </div>
        <br>
        <input type="submit" class="button green-bg" value="Login" style="width:100%"/>
        <hr style="width:28.5%">
    </form>
</div>
<div class="container">
  <p>Dont have an account? <a href="/register/?next={{ next }}"><b>Register</b></a></p>
  <p>Forgot your password? <a href="/reset-password/"><b>Reset it</b></a></p>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" >
    $(document).ready(function(){
        $("#id_username").attr('placeholder', '{{form.username.label}}');
        $("#id_password").attr('placeholder', '{{form.password.label}}');
    });
</script>
{% endblock pagecontent %}

src/faypublic/templates/user_password_reset.html
{% extends 'base.html' %}

{% block title %}Password reset{% endblock title %}

{% block pagecontent %}

<div class="container">
    <h1>Password reset</h1>
    <p>Forgot your password? No worries, use the form below to reset it!</p>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button green-bg" value="Send Reset Link"/>
    </form>
</div>

{% endblock pagecontent %}

src/faypublic/templates/user_password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock title %}

{% block pagecontent %}

<div class="container">
    <h1>Password reset complete</h1>
    <p>Please <a href="/login/">Log in</a> with your new password to access your account</p>
</div>

{% endblock pagecontent %}

src/faypublic/templates/user_password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock title %}

{% block pagecontent %}

<div class="container">
    <h1>Reset password</h1>
    <p>You have completed the email verification, please enter a new password below.</p>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button green-bg" value="Submit"/>
    </form>
</div>

{% endblock pagecontent %}

src/faypublic/templates/user_password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password reset sent{% endblock title %}

{% block pagecontent %}

<div class="container">
    <h1>Password reset sent</h1>
    <p>Check your email for instructions on resetting your password. If you did not receive an email, please verify that the email you entered belongs to your account.</p>
</div>

{% endblock pagecontent %}